/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-09 17:08:39 UTC)
 * on 2014-07-23 at 13:12:06 UTC 
 * Modify at your own risk.
 */

package com.snoozi.userendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String city;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String country;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long lastwakeup;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer likecount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pseudo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long signupstamp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer videocount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer viewcount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer wakeupcount;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCity() {
    return city;
  }

  /**
   * @param city city or {@code null} for none
   */
  public User setCity(java.lang.String city) {
    this.city = city;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCountry() {
    return country;
  }

  /**
   * @param country country or {@code null} for none
   */
  public User setCountry(java.lang.String country) {
    this.country = country;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public User setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public User setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLastwakeup() {
    return lastwakeup;
  }

  /**
   * @param lastwakeup lastwakeup or {@code null} for none
   */
  public User setLastwakeup(java.lang.Long lastwakeup) {
    this.lastwakeup = lastwakeup;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLikecount() {
    return likecount;
  }

  /**
   * @param likecount likecount or {@code null} for none
   */
  public User setLikecount(java.lang.Integer likecount) {
    this.likecount = likecount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPseudo() {
    return pseudo;
  }

  /**
   * @param pseudo pseudo or {@code null} for none
   */
  public User setPseudo(java.lang.String pseudo) {
    this.pseudo = pseudo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSignupstamp() {
    return signupstamp;
  }

  /**
   * @param signupstamp signupstamp or {@code null} for none
   */
  public User setSignupstamp(java.lang.Long signupstamp) {
    this.signupstamp = signupstamp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getVideocount() {
    return videocount;
  }

  /**
   * @param videocount videocount or {@code null} for none
   */
  public User setVideocount(java.lang.Integer videocount) {
    this.videocount = videocount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getViewcount() {
    return viewcount;
  }

  /**
   * @param viewcount viewcount or {@code null} for none
   */
  public User setViewcount(java.lang.Integer viewcount) {
    this.viewcount = viewcount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getWakeupcount() {
    return wakeupcount;
  }

  /**
   * @param wakeupcount wakeupcount or {@code null} for none
   */
  public User setWakeupcount(java.lang.Integer wakeupcount) {
    this.wakeupcount = wakeupcount;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
