/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-03 at 16:06:42 UTC 
 * Modify at your own risk.
 */

package com.snoozi.commentsendpoint;

/**
 * Service definition for Commentsendpoint (v4).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CommentsendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Commentsendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the commentsendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://4-dot-evident-quasar-565.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "commentsendpoint/v4/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Commentsendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Commentsendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getComments".
   *
   * This request holds the parameters needed by the commentsendpoint server.  After setting any
   * optional parameters, call the {@link GetComments#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetComments getComments(java.lang.Long id) throws java.io.IOException {
    GetComments result = new GetComments(id);
    initialize(result);
    return result;
  }

  public class GetComments extends CommentsendpointRequest<com.snoozi.commentsendpoint.model.Comments> {

    private static final String REST_PATH = "comments/{id}";

    /**
     * Create a request for the method "getComments".
     *
     * This request holds the parameters needed by the the commentsendpoint server.  After setting any
     * optional parameters, call the {@link GetComments#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetComments#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetComments(java.lang.Long id) {
      super(Commentsendpoint.this, "GET", REST_PATH, null, com.snoozi.commentsendpoint.model.Comments.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetComments setAlt(java.lang.String alt) {
      return (GetComments) super.setAlt(alt);
    }

    @Override
    public GetComments setFields(java.lang.String fields) {
      return (GetComments) super.setFields(fields);
    }

    @Override
    public GetComments setKey(java.lang.String key) {
      return (GetComments) super.setKey(key);
    }

    @Override
    public GetComments setOauthToken(java.lang.String oauthToken) {
      return (GetComments) super.setOauthToken(oauthToken);
    }

    @Override
    public GetComments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetComments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetComments setQuotaUser(java.lang.String quotaUser) {
      return (GetComments) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetComments setUserIp(java.lang.String userIp) {
      return (GetComments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetComments setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetComments set(String parameterName, Object value) {
      return (GetComments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getCommentsFromVideo".
   *
   * This request holds the parameters needed by the commentsendpoint server.  After setting any
   * optional parameters, call the {@link GetCommentsFromVideo#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetCommentsFromVideo getCommentsFromVideo() throws java.io.IOException {
    GetCommentsFromVideo result = new GetCommentsFromVideo();
    initialize(result);
    return result;
  }

  public class GetCommentsFromVideo extends CommentsendpointRequest<com.snoozi.commentsendpoint.model.CollectionResponseComments> {

    private static final String REST_PATH = "getCommentsFromVideo";

    /**
     * Create a request for the method "getCommentsFromVideo".
     *
     * This request holds the parameters needed by the the commentsendpoint server.  After setting any
     * optional parameters, call the {@link GetCommentsFromVideo#execute()} method to invoke the
     * remote operation. <p> {@link GetCommentsFromVideo#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetCommentsFromVideo() {
      super(Commentsendpoint.this, "GET", REST_PATH, null, com.snoozi.commentsendpoint.model.CollectionResponseComments.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCommentsFromVideo setAlt(java.lang.String alt) {
      return (GetCommentsFromVideo) super.setAlt(alt);
    }

    @Override
    public GetCommentsFromVideo setFields(java.lang.String fields) {
      return (GetCommentsFromVideo) super.setFields(fields);
    }

    @Override
    public GetCommentsFromVideo setKey(java.lang.String key) {
      return (GetCommentsFromVideo) super.setKey(key);
    }

    @Override
    public GetCommentsFromVideo setOauthToken(java.lang.String oauthToken) {
      return (GetCommentsFromVideo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCommentsFromVideo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCommentsFromVideo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCommentsFromVideo setQuotaUser(java.lang.String quotaUser) {
      return (GetCommentsFromVideo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCommentsFromVideo setUserIp(java.lang.String userIp) {
      return (GetCommentsFromVideo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public GetCommentsFromVideo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public GetCommentsFromVideo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long fromstamp;

    /**

     */
    public java.lang.Long getFromstamp() {
      return fromstamp;
    }

    public GetCommentsFromVideo setFromstamp(java.lang.Long fromstamp) {
      this.fromstamp = fromstamp;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long videoid;

    /**

     */
    public java.lang.Long getVideoid() {
      return videoid;
    }

    public GetCommentsFromVideo setVideoid(java.lang.Long videoid) {
      this.videoid = videoid;
      return this;
    }

    @Override
    public GetCommentsFromVideo set(String parameterName, Object value) {
      return (GetCommentsFromVideo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertComments".
   *
   * This request holds the parameters needed by the commentsendpoint server.  After setting any
   * optional parameters, call the {@link InsertComments#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.snoozi.commentsendpoint.model.Comments}
   * @return the request
   */
  public InsertComments insertComments(com.snoozi.commentsendpoint.model.Comments content) throws java.io.IOException {
    InsertComments result = new InsertComments(content);
    initialize(result);
    return result;
  }

  public class InsertComments extends CommentsendpointRequest<com.snoozi.commentsendpoint.model.Comments> {

    private static final String REST_PATH = "comments";

    /**
     * Create a request for the method "insertComments".
     *
     * This request holds the parameters needed by the the commentsendpoint server.  After setting any
     * optional parameters, call the {@link InsertComments#execute()} method to invoke the remote
     * operation. <p> {@link InsertComments#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.snoozi.commentsendpoint.model.Comments}
     * @since 1.13
     */
    protected InsertComments(com.snoozi.commentsendpoint.model.Comments content) {
      super(Commentsendpoint.this, "POST", REST_PATH, content, com.snoozi.commentsendpoint.model.Comments.class);
    }

    @Override
    public InsertComments setAlt(java.lang.String alt) {
      return (InsertComments) super.setAlt(alt);
    }

    @Override
    public InsertComments setFields(java.lang.String fields) {
      return (InsertComments) super.setFields(fields);
    }

    @Override
    public InsertComments setKey(java.lang.String key) {
      return (InsertComments) super.setKey(key);
    }

    @Override
    public InsertComments setOauthToken(java.lang.String oauthToken) {
      return (InsertComments) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertComments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertComments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertComments setQuotaUser(java.lang.String quotaUser) {
      return (InsertComments) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertComments setUserIp(java.lang.String userIp) {
      return (InsertComments) super.setUserIp(userIp);
    }

    @Override
    public InsertComments set(String parameterName, Object value) {
      return (InsertComments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listComments".
   *
   * This request holds the parameters needed by the commentsendpoint server.  After setting any
   * optional parameters, call the {@link ListComments#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListComments listComments() throws java.io.IOException {
    ListComments result = new ListComments();
    initialize(result);
    return result;
  }

  public class ListComments extends CommentsendpointRequest<com.snoozi.commentsendpoint.model.CollectionResponseComments> {

    private static final String REST_PATH = "comments";

    /**
     * Create a request for the method "listComments".
     *
     * This request holds the parameters needed by the the commentsendpoint server.  After setting any
     * optional parameters, call the {@link ListComments#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListComments#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListComments() {
      super(Commentsendpoint.this, "GET", REST_PATH, null, com.snoozi.commentsendpoint.model.CollectionResponseComments.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListComments setAlt(java.lang.String alt) {
      return (ListComments) super.setAlt(alt);
    }

    @Override
    public ListComments setFields(java.lang.String fields) {
      return (ListComments) super.setFields(fields);
    }

    @Override
    public ListComments setKey(java.lang.String key) {
      return (ListComments) super.setKey(key);
    }

    @Override
    public ListComments setOauthToken(java.lang.String oauthToken) {
      return (ListComments) super.setOauthToken(oauthToken);
    }

    @Override
    public ListComments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListComments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListComments setQuotaUser(java.lang.String quotaUser) {
      return (ListComments) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListComments setUserIp(java.lang.String userIp) {
      return (ListComments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListComments setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListComments setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListComments set(String parameterName, Object value) {
      return (ListComments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRecentComments".
   *
   * This request holds the parameters needed by the commentsendpoint server.  After setting any
   * optional parameters, call the {@link ListRecentComments#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListRecentComments listRecentComments() throws java.io.IOException {
    ListRecentComments result = new ListRecentComments();
    initialize(result);
    return result;
  }

  public class ListRecentComments extends CommentsendpointRequest<com.snoozi.commentsendpoint.model.CollectionResponseComments> {

    private static final String REST_PATH = "listRecentComments";

    /**
     * Create a request for the method "listRecentComments".
     *
     * This request holds the parameters needed by the the commentsendpoint server.  After setting any
     * optional parameters, call the {@link ListRecentComments#execute()} method to invoke the remote
     * operation. <p> {@link ListRecentComments#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRecentComments() {
      super(Commentsendpoint.this, "GET", REST_PATH, null, com.snoozi.commentsendpoint.model.CollectionResponseComments.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRecentComments setAlt(java.lang.String alt) {
      return (ListRecentComments) super.setAlt(alt);
    }

    @Override
    public ListRecentComments setFields(java.lang.String fields) {
      return (ListRecentComments) super.setFields(fields);
    }

    @Override
    public ListRecentComments setKey(java.lang.String key) {
      return (ListRecentComments) super.setKey(key);
    }

    @Override
    public ListRecentComments setOauthToken(java.lang.String oauthToken) {
      return (ListRecentComments) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRecentComments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRecentComments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRecentComments setQuotaUser(java.lang.String quotaUser) {
      return (ListRecentComments) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRecentComments setUserIp(java.lang.String userIp) {
      return (ListRecentComments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRecentComments setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRecentComments setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRecentComments set(String parameterName, Object value) {
      return (ListRecentComments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeComments".
   *
   * This request holds the parameters needed by the commentsendpoint server.  After setting any
   * optional parameters, call the {@link RemoveComments#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveComments removeComments(java.lang.Long id) throws java.io.IOException {
    RemoveComments result = new RemoveComments(id);
    initialize(result);
    return result;
  }

  public class RemoveComments extends CommentsendpointRequest<Void> {

    private static final String REST_PATH = "comments/{id}";

    /**
     * Create a request for the method "removeComments".
     *
     * This request holds the parameters needed by the the commentsendpoint server.  After setting any
     * optional parameters, call the {@link RemoveComments#execute()} method to invoke the remote
     * operation. <p> {@link RemoveComments#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveComments(java.lang.Long id) {
      super(Commentsendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveComments setAlt(java.lang.String alt) {
      return (RemoveComments) super.setAlt(alt);
    }

    @Override
    public RemoveComments setFields(java.lang.String fields) {
      return (RemoveComments) super.setFields(fields);
    }

    @Override
    public RemoveComments setKey(java.lang.String key) {
      return (RemoveComments) super.setKey(key);
    }

    @Override
    public RemoveComments setOauthToken(java.lang.String oauthToken) {
      return (RemoveComments) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveComments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveComments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveComments setQuotaUser(java.lang.String quotaUser) {
      return (RemoveComments) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveComments setUserIp(java.lang.String userIp) {
      return (RemoveComments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveComments setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveComments set(String parameterName, Object value) {
      return (RemoveComments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateComments".
   *
   * This request holds the parameters needed by the commentsendpoint server.  After setting any
   * optional parameters, call the {@link UpdateComments#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.snoozi.commentsendpoint.model.Comments}
   * @return the request
   */
  public UpdateComments updateComments(com.snoozi.commentsendpoint.model.Comments content) throws java.io.IOException {
    UpdateComments result = new UpdateComments(content);
    initialize(result);
    return result;
  }

  public class UpdateComments extends CommentsendpointRequest<com.snoozi.commentsendpoint.model.Comments> {

    private static final String REST_PATH = "comments";

    /**
     * Create a request for the method "updateComments".
     *
     * This request holds the parameters needed by the the commentsendpoint server.  After setting any
     * optional parameters, call the {@link UpdateComments#execute()} method to invoke the remote
     * operation. <p> {@link UpdateComments#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.snoozi.commentsendpoint.model.Comments}
     * @since 1.13
     */
    protected UpdateComments(com.snoozi.commentsendpoint.model.Comments content) {
      super(Commentsendpoint.this, "PUT", REST_PATH, content, com.snoozi.commentsendpoint.model.Comments.class);
    }

    @Override
    public UpdateComments setAlt(java.lang.String alt) {
      return (UpdateComments) super.setAlt(alt);
    }

    @Override
    public UpdateComments setFields(java.lang.String fields) {
      return (UpdateComments) super.setFields(fields);
    }

    @Override
    public UpdateComments setKey(java.lang.String key) {
      return (UpdateComments) super.setKey(key);
    }

    @Override
    public UpdateComments setOauthToken(java.lang.String oauthToken) {
      return (UpdateComments) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateComments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateComments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateComments setQuotaUser(java.lang.String quotaUser) {
      return (UpdateComments) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateComments setUserIp(java.lang.String userIp) {
      return (UpdateComments) super.setUserIp(userIp);
    }

    @Override
    public UpdateComments set(String parameterName, Object value) {
      return (UpdateComments) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Commentsendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Commentsendpoint}. */
    @Override
    public Commentsendpoint build() {
      return new Commentsendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CommentsendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCommentsendpointRequestInitializer(
        CommentsendpointRequestInitializer commentsendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(commentsendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
