/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-03 at 16:07:11 UTC 
 * Modify at your own risk.
 */

package com.snoozi.alarmendpoint.model;

/**
 * Model definition for Alarm.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the alarmendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Alarm extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean activate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String daystring;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean friday;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer hour;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer minute;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean monday;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean saturday;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean sunday;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean thursday;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean tuesday;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean vibrate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long videoid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer volume;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean wednesday;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getActivate() {
    return activate;
  }

  /**
   * @param activate activate or {@code null} for none
   */
  public Alarm setActivate(java.lang.Boolean activate) {
    this.activate = activate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDaystring() {
    return daystring;
  }

  /**
   * @param daystring daystring or {@code null} for none
   */
  public Alarm setDaystring(java.lang.String daystring) {
    this.daystring = daystring;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getFriday() {
    return friday;
  }

  /**
   * @param friday friday or {@code null} for none
   */
  public Alarm setFriday(java.lang.Boolean friday) {
    this.friday = friday;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getHour() {
    return hour;
  }

  /**
   * @param hour hour or {@code null} for none
   */
  public Alarm setHour(java.lang.Integer hour) {
    this.hour = hour;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Alarm setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMinute() {
    return minute;
  }

  /**
   * @param minute minute or {@code null} for none
   */
  public Alarm setMinute(java.lang.Integer minute) {
    this.minute = minute;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getMonday() {
    return monday;
  }

  /**
   * @param monday monday or {@code null} for none
   */
  public Alarm setMonday(java.lang.Boolean monday) {
    this.monday = monday;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSaturday() {
    return saturday;
  }

  /**
   * @param saturday saturday or {@code null} for none
   */
  public Alarm setSaturday(java.lang.Boolean saturday) {
    this.saturday = saturday;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public Alarm setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSunday() {
    return sunday;
  }

  /**
   * @param sunday sunday or {@code null} for none
   */
  public Alarm setSunday(java.lang.Boolean sunday) {
    this.sunday = sunday;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getThursday() {
    return thursday;
  }

  /**
   * @param thursday thursday or {@code null} for none
   */
  public Alarm setThursday(java.lang.Boolean thursday) {
    this.thursday = thursday;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getTuesday() {
    return tuesday;
  }

  /**
   * @param tuesday tuesday or {@code null} for none
   */
  public Alarm setTuesday(java.lang.Boolean tuesday) {
    this.tuesday = tuesday;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserid() {
    return userid;
  }

  /**
   * @param userid userid or {@code null} for none
   */
  public Alarm setUserid(java.lang.Long userid) {
    this.userid = userid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getVibrate() {
    return vibrate;
  }

  /**
   * @param vibrate vibrate or {@code null} for none
   */
  public Alarm setVibrate(java.lang.Boolean vibrate) {
    this.vibrate = vibrate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVideoid() {
    return videoid;
  }

  /**
   * @param videoid videoid or {@code null} for none
   */
  public Alarm setVideoid(java.lang.Long videoid) {
    this.videoid = videoid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getVolume() {
    return volume;
  }

  /**
   * @param volume volume or {@code null} for none
   */
  public Alarm setVolume(java.lang.Integer volume) {
    this.volume = volume;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getWednesday() {
    return wednesday;
  }

  /**
   * @param wednesday wednesday or {@code null} for none
   */
  public Alarm setWednesday(java.lang.Boolean wednesday) {
    this.wednesday = wednesday;
    return this;
  }

  @Override
  public Alarm set(String fieldName, Object value) {
    return (Alarm) super.set(fieldName, value);
  }

  @Override
  public Alarm clone() {
    return (Alarm) super.clone();
  }

}
