/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-09 17:08:39 UTC)
 * on 2014-07-23 at 18:48:14 UTC 
 * Modify at your own risk.
 */

package com.snoozi.trackingeventendpoint;

/**
 * Service definition for Trackingeventendpoint (v4).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TrackingeventendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Trackingeventendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the trackingeventendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://4-dot-evident-quasar-565.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "trackingeventendpoint/v4/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Trackingeventendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Trackingeventendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getTrackingEvent".
   *
   * This request holds the parameters needed by the trackingeventendpoint server.  After setting any
   * optional parameters, call the {@link GetTrackingEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetTrackingEvent getTrackingEvent(java.lang.Long id) throws java.io.IOException {
    GetTrackingEvent result = new GetTrackingEvent(id);
    initialize(result);
    return result;
  }

  public class GetTrackingEvent extends TrackingeventendpointRequest<com.snoozi.trackingeventendpoint.model.TrackingEvent> {

    private static final String REST_PATH = "trackingevent/{id}";

    /**
     * Create a request for the method "getTrackingEvent".
     *
     * This request holds the parameters needed by the the trackingeventendpoint server.  After
     * setting any optional parameters, call the {@link GetTrackingEvent#execute()} method to invoke
     * the remote operation. <p> {@link GetTrackingEvent#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTrackingEvent(java.lang.Long id) {
      super(Trackingeventendpoint.this, "GET", REST_PATH, null, com.snoozi.trackingeventendpoint.model.TrackingEvent.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTrackingEvent setAlt(java.lang.String alt) {
      return (GetTrackingEvent) super.setAlt(alt);
    }

    @Override
    public GetTrackingEvent setFields(java.lang.String fields) {
      return (GetTrackingEvent) super.setFields(fields);
    }

    @Override
    public GetTrackingEvent setKey(java.lang.String key) {
      return (GetTrackingEvent) super.setKey(key);
    }

    @Override
    public GetTrackingEvent setOauthToken(java.lang.String oauthToken) {
      return (GetTrackingEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTrackingEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTrackingEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTrackingEvent setQuotaUser(java.lang.String quotaUser) {
      return (GetTrackingEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTrackingEvent setUserIp(java.lang.String userIp) {
      return (GetTrackingEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetTrackingEvent setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTrackingEvent set(String parameterName, Object value) {
      return (GetTrackingEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertTrackingEvent".
   *
   * This request holds the parameters needed by the trackingeventendpoint server.  After setting any
   * optional parameters, call the {@link InsertTrackingEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.snoozi.trackingeventendpoint.model.TrackingEvent}
   * @return the request
   */
  public InsertTrackingEvent insertTrackingEvent(com.snoozi.trackingeventendpoint.model.TrackingEvent content) throws java.io.IOException {
    InsertTrackingEvent result = new InsertTrackingEvent(content);
    initialize(result);
    return result;
  }

  public class InsertTrackingEvent extends TrackingeventendpointRequest<com.snoozi.trackingeventendpoint.model.TrackingEvent> {

    private static final String REST_PATH = "trackingevent";

    /**
     * Create a request for the method "insertTrackingEvent".
     *
     * This request holds the parameters needed by the the trackingeventendpoint server.  After
     * setting any optional parameters, call the {@link InsertTrackingEvent#execute()} method to
     * invoke the remote operation. <p> {@link InsertTrackingEvent#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.snoozi.trackingeventendpoint.model.TrackingEvent}
     * @since 1.13
     */
    protected InsertTrackingEvent(com.snoozi.trackingeventendpoint.model.TrackingEvent content) {
      super(Trackingeventendpoint.this, "POST", REST_PATH, content, com.snoozi.trackingeventendpoint.model.TrackingEvent.class);
    }

    @Override
    public InsertTrackingEvent setAlt(java.lang.String alt) {
      return (InsertTrackingEvent) super.setAlt(alt);
    }

    @Override
    public InsertTrackingEvent setFields(java.lang.String fields) {
      return (InsertTrackingEvent) super.setFields(fields);
    }

    @Override
    public InsertTrackingEvent setKey(java.lang.String key) {
      return (InsertTrackingEvent) super.setKey(key);
    }

    @Override
    public InsertTrackingEvent setOauthToken(java.lang.String oauthToken) {
      return (InsertTrackingEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertTrackingEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertTrackingEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertTrackingEvent setQuotaUser(java.lang.String quotaUser) {
      return (InsertTrackingEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertTrackingEvent setUserIp(java.lang.String userIp) {
      return (InsertTrackingEvent) super.setUserIp(userIp);
    }

    @Override
    public InsertTrackingEvent set(String parameterName, Object value) {
      return (InsertTrackingEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTrackingEvent".
   *
   * This request holds the parameters needed by the trackingeventendpoint server.  After setting any
   * optional parameters, call the {@link ListTrackingEvent#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTrackingEvent listTrackingEvent() throws java.io.IOException {
    ListTrackingEvent result = new ListTrackingEvent();
    initialize(result);
    return result;
  }

  public class ListTrackingEvent extends TrackingeventendpointRequest<com.snoozi.trackingeventendpoint.model.CollectionResponseTrackingEvent> {

    private static final String REST_PATH = "trackingevent";

    /**
     * Create a request for the method "listTrackingEvent".
     *
     * This request holds the parameters needed by the the trackingeventendpoint server.  After
     * setting any optional parameters, call the {@link ListTrackingEvent#execute()} method to invoke
     * the remote operation. <p> {@link ListTrackingEvent#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTrackingEvent() {
      super(Trackingeventendpoint.this, "GET", REST_PATH, null, com.snoozi.trackingeventendpoint.model.CollectionResponseTrackingEvent.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTrackingEvent setAlt(java.lang.String alt) {
      return (ListTrackingEvent) super.setAlt(alt);
    }

    @Override
    public ListTrackingEvent setFields(java.lang.String fields) {
      return (ListTrackingEvent) super.setFields(fields);
    }

    @Override
    public ListTrackingEvent setKey(java.lang.String key) {
      return (ListTrackingEvent) super.setKey(key);
    }

    @Override
    public ListTrackingEvent setOauthToken(java.lang.String oauthToken) {
      return (ListTrackingEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTrackingEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTrackingEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTrackingEvent setQuotaUser(java.lang.String quotaUser) {
      return (ListTrackingEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTrackingEvent setUserIp(java.lang.String userIp) {
      return (ListTrackingEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTrackingEvent setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTrackingEvent setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTrackingEvent set(String parameterName, Object value) {
      return (ListTrackingEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeErrorLoggerEvent".
   *
   * This request holds the parameters needed by the trackingeventendpoint server.  After setting any
   * optional parameters, call the {@link RemoveErrorLoggerEvent#execute()} method to invoke the
   * remote operation.
   *
   * @return the request
   */
  public RemoveErrorLoggerEvent removeErrorLoggerEvent() throws java.io.IOException {
    RemoveErrorLoggerEvent result = new RemoveErrorLoggerEvent();
    initialize(result);
    return result;
  }

  public class RemoveErrorLoggerEvent extends TrackingeventendpointRequest<Void> {

    private static final String REST_PATH = "errorloggerevent";

    /**
     * Create a request for the method "removeErrorLoggerEvent".
     *
     * This request holds the parameters needed by the the trackingeventendpoint server.  After
     * setting any optional parameters, call the {@link RemoveErrorLoggerEvent#execute()} method to
     * invoke the remote operation. <p> {@link RemoveErrorLoggerEvent#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected RemoveErrorLoggerEvent() {
      super(Trackingeventendpoint.this, "DELETE", REST_PATH, null, Void.class);
    }

    @Override
    public RemoveErrorLoggerEvent setAlt(java.lang.String alt) {
      return (RemoveErrorLoggerEvent) super.setAlt(alt);
    }

    @Override
    public RemoveErrorLoggerEvent setFields(java.lang.String fields) {
      return (RemoveErrorLoggerEvent) super.setFields(fields);
    }

    @Override
    public RemoveErrorLoggerEvent setKey(java.lang.String key) {
      return (RemoveErrorLoggerEvent) super.setKey(key);
    }

    @Override
    public RemoveErrorLoggerEvent setOauthToken(java.lang.String oauthToken) {
      return (RemoveErrorLoggerEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveErrorLoggerEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveErrorLoggerEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveErrorLoggerEvent setQuotaUser(java.lang.String quotaUser) {
      return (RemoveErrorLoggerEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveErrorLoggerEvent setUserIp(java.lang.String userIp) {
      return (RemoveErrorLoggerEvent) super.setUserIp(userIp);
    }

    @Override
    public RemoveErrorLoggerEvent set(String parameterName, Object value) {
      return (RemoveErrorLoggerEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeTrackingEvent".
   *
   * This request holds the parameters needed by the trackingeventendpoint server.  After setting any
   * optional parameters, call the {@link RemoveTrackingEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveTrackingEvent removeTrackingEvent(java.lang.Long id) throws java.io.IOException {
    RemoveTrackingEvent result = new RemoveTrackingEvent(id);
    initialize(result);
    return result;
  }

  public class RemoveTrackingEvent extends TrackingeventendpointRequest<Void> {

    private static final String REST_PATH = "trackingevent/{id}";

    /**
     * Create a request for the method "removeTrackingEvent".
     *
     * This request holds the parameters needed by the the trackingeventendpoint server.  After
     * setting any optional parameters, call the {@link RemoveTrackingEvent#execute()} method to
     * invoke the remote operation. <p> {@link RemoveTrackingEvent#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveTrackingEvent(java.lang.Long id) {
      super(Trackingeventendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveTrackingEvent setAlt(java.lang.String alt) {
      return (RemoveTrackingEvent) super.setAlt(alt);
    }

    @Override
    public RemoveTrackingEvent setFields(java.lang.String fields) {
      return (RemoveTrackingEvent) super.setFields(fields);
    }

    @Override
    public RemoveTrackingEvent setKey(java.lang.String key) {
      return (RemoveTrackingEvent) super.setKey(key);
    }

    @Override
    public RemoveTrackingEvent setOauthToken(java.lang.String oauthToken) {
      return (RemoveTrackingEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveTrackingEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveTrackingEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveTrackingEvent setQuotaUser(java.lang.String quotaUser) {
      return (RemoveTrackingEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveTrackingEvent setUserIp(java.lang.String userIp) {
      return (RemoveTrackingEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveTrackingEvent setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveTrackingEvent set(String parameterName, Object value) {
      return (RemoveTrackingEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateTrackingEvent".
   *
   * This request holds the parameters needed by the trackingeventendpoint server.  After setting any
   * optional parameters, call the {@link UpdateTrackingEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.snoozi.trackingeventendpoint.model.TrackingEvent}
   * @return the request
   */
  public UpdateTrackingEvent updateTrackingEvent(com.snoozi.trackingeventendpoint.model.TrackingEvent content) throws java.io.IOException {
    UpdateTrackingEvent result = new UpdateTrackingEvent(content);
    initialize(result);
    return result;
  }

  public class UpdateTrackingEvent extends TrackingeventendpointRequest<com.snoozi.trackingeventendpoint.model.TrackingEvent> {

    private static final String REST_PATH = "trackingevent";

    /**
     * Create a request for the method "updateTrackingEvent".
     *
     * This request holds the parameters needed by the the trackingeventendpoint server.  After
     * setting any optional parameters, call the {@link UpdateTrackingEvent#execute()} method to
     * invoke the remote operation. <p> {@link UpdateTrackingEvent#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.snoozi.trackingeventendpoint.model.TrackingEvent}
     * @since 1.13
     */
    protected UpdateTrackingEvent(com.snoozi.trackingeventendpoint.model.TrackingEvent content) {
      super(Trackingeventendpoint.this, "PUT", REST_PATH, content, com.snoozi.trackingeventendpoint.model.TrackingEvent.class);
    }

    @Override
    public UpdateTrackingEvent setAlt(java.lang.String alt) {
      return (UpdateTrackingEvent) super.setAlt(alt);
    }

    @Override
    public UpdateTrackingEvent setFields(java.lang.String fields) {
      return (UpdateTrackingEvent) super.setFields(fields);
    }

    @Override
    public UpdateTrackingEvent setKey(java.lang.String key) {
      return (UpdateTrackingEvent) super.setKey(key);
    }

    @Override
    public UpdateTrackingEvent setOauthToken(java.lang.String oauthToken) {
      return (UpdateTrackingEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateTrackingEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateTrackingEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateTrackingEvent setQuotaUser(java.lang.String quotaUser) {
      return (UpdateTrackingEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateTrackingEvent setUserIp(java.lang.String userIp) {
      return (UpdateTrackingEvent) super.setUserIp(userIp);
    }

    @Override
    public UpdateTrackingEvent set(String parameterName, Object value) {
      return (UpdateTrackingEvent) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Trackingeventendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Trackingeventendpoint}. */
    @Override
    public Trackingeventendpoint build() {
      return new Trackingeventendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TrackingeventendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTrackingeventendpointRequestInitializer(
        TrackingeventendpointRequestInitializer trackingeventendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(trackingeventendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
