/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-09 17:08:39 UTC)
 * on 2014-07-23 at 13:14:37 UTC 
 * Modify at your own risk.
 */

package com.snoozi.uservideoendpoint.model;

/**
 * Model definition for UserVideo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the uservideoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserVideo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isFavorite;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer likecount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long videoid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer viewcount;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public UserVideo setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsFavorite() {
    return isFavorite;
  }

  /**
   * @param isFavorite isFavorite or {@code null} for none
   */
  public UserVideo setIsFavorite(java.lang.Boolean isFavorite) {
    this.isFavorite = isFavorite;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLikecount() {
    return likecount;
  }

  /**
   * @param likecount likecount or {@code null} for none
   */
  public UserVideo setLikecount(java.lang.Integer likecount) {
    this.likecount = likecount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserid() {
    return userid;
  }

  /**
   * @param userid userid or {@code null} for none
   */
  public UserVideo setUserid(java.lang.Long userid) {
    this.userid = userid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVideoid() {
    return videoid;
  }

  /**
   * @param videoid videoid or {@code null} for none
   */
  public UserVideo setVideoid(java.lang.Long videoid) {
    this.videoid = videoid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getViewcount() {
    return viewcount;
  }

  /**
   * @param viewcount viewcount or {@code null} for none
   */
  public UserVideo setViewcount(java.lang.Integer viewcount) {
    this.viewcount = viewcount;
    return this;
  }

  @Override
  public UserVideo set(String fieldName, Object value) {
    return (UserVideo) super.set(fieldName, value);
  }

  @Override
  public UserVideo clone() {
    return (UserVideo) super.clone();
  }

}
